"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("rooms", [
      {
        name: "Room 1001",
        room_type_id: 1,
        room_level_id: 1,
        status: "available",
        description: "A cozy single room with a bed and a desk.",
        floor_id: 1,
      },
      {
        name: "Room 1002",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1003",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1004",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1005",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1006",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1007",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1008",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1009",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1010",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1011",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1012",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1013",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1014",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1015",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1016",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1017",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1018",
        room_type_id: 2,
        room_level_id: 2,
        status: "available",
        description: "A spacious double room with a nice view.",
        floor_id: 1,
      },
      {
        name: "Room 1019",
        room_type_id: 3,
        room_level_id: 3,
        status: "available",
        description: "A luxurious suite with all amenities.",
        floor_id: 1,
      },
      {
        name: "Room 1020",
        room_type_id: 3,
        room_level_id: 3,
        status: "available",
        description: "A luxurious suite with all amenities.",
        floor_id: 1,
      },
      {
        name: "Room 2001",
        room_type_id: 3,
        room_level_id: 3,
        status: "available",
        description: "A luxurious suite with all amenities.",
        floor_id: 2,
      },
      {
        name: "Room 2002",
        room_type_id: 3,
        room_level_id: 3,
        status: "available",
        description: "A luxurious suite with all amenities.",
        floor_id: 2,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("rooms", null, {});
  },
};
